// export { default as ic_comment } from './icon/ic_comment.svg'
export { default as nvidia_logo } from './CompanyIcons/nvidia.png'
export { default as light_bulb } from './icons/lightbulb.png'
export { default as emptyImg } from './icons/emptyImg.jpg'
export { default as human } from './icons/Entrepreneur.jpg'