// export { default as ic_comment } from './icon/ic_comment.svg'
export { default as nvidia_logo } from './CompanyIcons/nvidia.png'
export { default as light_bulb } from './icons/lightbulb.png'
export { default as emptyImg } from './icons/emptyImg.jpg'
export { default as GoogleIcon } from './CompanyIcons/google.png'
export { default as human } from './icons/Entrepreneur.jpg'
export { default as startup } from './icons/startupCEO.webp'
export { default as smallCompany } from './icons/smallCompanyCEO.png'
export { default as companyCEO } from './icons/companyCEO.png'
export { default as money } from './icons/money.png'
export { default as usercompany } from './icons/usercompany.png'
export { default as usersell } from './icons/usersell.png'
export { default as companytodo } from './icons/companytodo.png'